title: Be to a better man
author: whoiami
description: wait, who am i?

highlighter: null
permalink: /:title

url:
baseurl:

sass:
  sass_dir: public/css
  style: :compressed

google_analytics_tracking_id: UA-113192930-1
